Выбор 4 магов из списка
htmlacademy-javascript/977171-code-and-magick-21 pull request #3
Opened 2020-10-12 16:12 UTC by RuDovbnySe

2020-10-12 18:09 UTC, frontstall requested changes

2020-10-12 18:09 UTC, frontstall commented on js/setup.js
> +var userDialog = document.querySelector('.setup');
Используй современный синтаксис для объявления переменных - const для переменных, которые не будут меняться, let для тех, которые будут мутированы. Это современный стандарт.

2020-10-12 18:09 UTC, frontstall commented on js/setup.js
> +var COAT_COLORS = ['rgb(101, 137, 164)', 'rgb(241, 43, 107)', 'rgb(146, 100, 161)', 'rgb(56, 159, 117)', 'rgb(215,' +
для массивов с большим числом элементов можно делать так:

```
const longList = [
  item,
  oneMoreItem,
  anotherOne,
];
```

Разрывать через конкатенацию не нужно, это неочевидно.

2020-10-12 18:09 UTC, frontstall commented on js/setup.js
> +  let HeroName = function arrayRandElement(WIZARD_NAMES) {
названия функций с маленькой буквы. Найти такие ошибки помогает вывод линтера в билде тревиса: https://travis-ci.com/github/htmlacademy-javascript/977171-code-and-magick-21/builds/189530174

`HeroName` - это функция, название должно начинаться с глагола.

Кажется, пора созвониться :)

2020-10-14 21:26 UTC, RuDovbnySe commented on js/setup.js
> +var COAT_COLORS = ['rgb(101, 137, 164)', 'rgb(241, 43, 107)', 'rgb(146, 100, 161)', 'rgb(56, 159, 117)', 'rgb(215,' +
Оставим вопрос на следующую сессию. Сделал так, всё сломалось.

2020-10-17 10:34 UTC, frontstall commented on js/setup.js
> +const WIZARD_NAMES = ['Иван', 'Хуан Себастьян', 'Мария', 'Кристоф', 'Виктор', 'Юлия', 'Люпита', 'Вашингтон'];
Все объявления констант находятся в самом верху, сразу после 'use strict';

2020-10-17 10:34 UTC, frontstall commented on js/setup.js
> +const COAT_COLORS = ['rgb(101, 137, 164)', 'rgb(241, 43, 107)', 'rgb(146, 100, 161)', 'rgb(56, 159, 117)', 'rgb(215,' +
Не нужно переносить строки через конкатенацию, в прошлом ревью я писал, как нужно.

2020-10-17 10:34 UTC, frontstall commented on js/setup.js
> +let wizards = [];
Это должна быть функция, которая генерирует одного волшебника. Затем эту функцию вызываем в цикле.

2020-10-17 10:34 UTC, frontstall commented on js/setup.js
> +for (let i = 0; i < 4; i++) {
4 - магическое число

2020-10-17 10:34 UTC, frontstall commented on js/setup.js
> +  const wizardFullName = wizarnName + ' ' + wizardSurname;
Используй интерполяцию вместо конкатенации

2020-10-17 10:34 UTC, frontstall commented on js/setup.js
> +  const generateWizardData =
Это не функция, а зовётся, как функция.

2020-10-17 10:34 UTC, frontstall commented on js/stat.js
> +let renderCloud = function (ctx, x, y, color) {
1) const
2) используй стрелочные функции

2020-10-17 10:34 UTC, merged